version: '3'
services:
  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:1.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - ORDERER_FILELEDGER_LOCATION=/etc/hyperledger/data
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=false
    ports:
      - 7050:7050
    volumes:
      - ./orderer/genesis.block:/etc/hyperledger/genesis.block
      - ./config/crypto-config/ordererOrganizations/orderer/users/Admin@orderer/msp:/etc/hyperledger/msp
      - ./orderer/data:/etc/hyperledger/data
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    network_mode: fabric
  org1.peer1:
    container_name: org1.peer1
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_PEER_ID=org1.peer1
      - CORE_PEER_ADDRESS=org1.peer1:7051
      - CORE_PEER_LISTENADDRESS=org1.peer1:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=org1.peer1:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ENDPOINT=org1.peer1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=org1.peer1:7051
      - CORE_PEER_EVENTS_ADDRESS=org1.peer1:7053
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/peer/msp
      - CORE_PEER_FILESYSTEMPATH=/peer/data
      - CORE_PEER_TLS_ENABLED=false
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4
      - CORE_PEER_NETWORKID=test
    ports:
      - 17051:7051
      - 17053:7053
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/crypto-config/peerOrganizations/org1/peers/peer1.org1/msp:/peer/msp
      - ./org1.peer1/data:/peer/data
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    depends_on:
      - orderer
    network_mode: fabric
  org1.peer2:
    container_name: org1.peer2
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ID=org1.peer2
      - CORE_PEER_ADDRESS=org1.peer2:7051
      - CORE_PEER_LISTENADDRESS=org1.peer2:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=org1.peer1:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ENDPOINT=org1.peer2:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=org1.peer2:7051
      - CORE_PEER_EVENTS_ADDRESS=org1.peer2:7053
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/peer/msp
      - CORE_PEER_FILESYSTEMPATH=/peer/data
      - CORE_PEER_TLS_ENABLED=false
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4
      - CORE_PEER_NETWORKID=test
    ports:
      - 27051:7051
      - 27053:7053
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/crypto-config/peerOrganizations/org1/peers/peer2.org1/msp:/peer/msp
      - ./org1.peer2/data:/peer/data
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    depends_on:
      - orderer
    network_mode: fabric
  org2.peer1:
    container_name: org2.peer1
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ID=org2.peer1
      - CORE_PEER_ADDRESS=org2.peer1:7051
      - CORE_PEER_LISTENADDRESS=org2.peer1:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=org1.peer1:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ENDPOINT=org2.peer1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=org2.peer1:7051
      - CORE_PEER_EVENTS_ADDRESS=org2.peer1:7053
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/peer/msp
      - CORE_PEER_FILESYSTEMPATH=/peer/data
      - CORE_PEER_TLS_ENABLED=false
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4
      - CORE_PEER_NETWORKID=test
    ports:
      - 37051:7051
      - 37053:7053
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/crypto-config/peerOrganizations/org2/peers/peer1.org2/msp:/peer/msp
      - ./org2.peer1/data:/peer/data
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    depends_on:
      - orderer
    network_mode: fabric
  org2.peer2:
    container_name: org2.peer2
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ID=org2.peer2
      - CORE_PEER_ADDRESS=org2.peer2:7051
      - CORE_PEER_LISTENADDRESS=org2.peer2:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=org1.peer1:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ENDPOINT=org2.peer2:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=org2.peer2:7051
      - CORE_PEER_EVENTS_ADDRESS=org2.peer2:7053
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/peer/msp
      - CORE_PEER_FILESYSTEMPATH=/peer/data
      - CORE_PEER_TLS_ENABLED=false
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4
      - CORE_PEER_NETWORKID=test
    ports:
      - 47051:7051
      - 47053:7053
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/crypto-config/peerOrganizations/org2/peers/peer2.org2/msp:/peer/msp
      - ./org2.peer2/data:/peer/data
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    depends_on:
      - orderer
    network_mode: fabric
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=org1.peer1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/admin/msp/org1Admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/crypto-config/ordererOrganizations/orderer/users/Admin@orderer/msp:/admin/msp/ordererAdmin
      - ./config/crypto-config/peerOrganizations/org1/users/Admin@org1/msp:/admin/msp/org1Admin
      - ./config/crypto-config/peerOrganizations/org2/users/Admin@org2/msp:/admin/msp/org2Admin
      - ./cli/data:/admin/data
      - ./cli/fabric/examples:/opt/gopath/src/github.com/hyperledger/fabric/examples
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    depends_on:
      - org1.peer1
      - org1.peer2
      - org2.peer1
      - org2.peer2
      - orderer
    command: tail -f /var/log/bootstrap.log
    network_mode: fabric
