# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: orderer
    EnableNodeOUs: false
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
    #SANS:
    #  - "orderer1"
    #  - "orderer2"
    #  - "orderer3"
PeerOrgs:
  - Name: Org1
    Domain: org1 
    EnableNodeOUs: false
    Specs:
      - Hostname: peer1
      - Hostname: peer2
    Template:
      Count: 2
    Users:  
      Count: 4
###############################################################################
  - Name: Org2  
    Domain: org2  
    EnableNodeOUs: false
    Specs:
      - Hostname: peer1
      - Hostname: peer2
    Template:  
      Count: 2  
    Users:  
      Count: 4  

